### ISSUE TITLE
Algorithm Description

### ISSUE THREAD

**Issue by saatkamp** [UST-QuAntiL/q-tal#1]
**As a** algorihm expert **I want** describe algorithm and their characteristics **so that** other experts can easily understand the functional and non-functional properties of an algorithm.
 
Most algorithms are described in publications. To enable experts to compare, discuss, and evaluate different algorithms and to collaborate with others, the algorithms and their characteristics must be accessible for the expert community. Therefore, the algorithms must be available on the collaboration platform.

### Product requirement

- New algorithms can be added.
- Owner of the algorithm can edit the content.
- An algorithm can be linked with the publications the algorithm is described in.
- An algorithm can refer to other algorithms with a specific semantic, e.g. the algorithm is an "improvment" of another algorithm or the algorithm is a "quantum-couterpart"
- Algorithms can also refer patterns that are contained in the algorithm or the patterns that is an abstraction of the algorithm
- Depending on the quantum computation model a different graphical representation of the algorithm can be used
- An Algorithm can be described by Problem Types to ease the search of relevant algorithms
- The required resources such as Qubits can be added to the algorithm

### Technical requirement
- Pattern IDs must be pulled from the Pattern Atlas
- Integration of the LaTex-Rendering Service

### Design requirement
- The experts want to upload either LaTeX or images for the graphical representation of the algorithm

>Note: Reference to RQ-1, RQ-3, RQ-69, partially RQ-43

**Comment by salmma** [comment]
done
