### ISSUE TITLE
Algorithm Implementation Description

### ISSUE THREAD

**Issue by saatkamp** [UST-QuAntiL/q-tal#2]
**As a** quantum-application expert / developer **I want** to provide my implementations of algorithms **so that** others can identify relevant implementations for their needs.

Algorithms describe the general solution for a given problem by the sequence of operations or linear system of equations. However, the algorithms cannot be executed directly, they have to be implemented for running on a specfic backend which can be simulators or real quantum processors.

Other experts and also use case owner or interested persons shall be able to identify implementations of algorithms of interest.

### Product requirement

- Implementation descriptions can be added.
- Owner of the Implementation can edit the content.
- Implementations are added for a particular algorithm they no not exist independently.
- Implementations have specific dependencies required to run the implementation, especially the software platform to compile and execute the implemented algorithm
- Implementations are also often referenced in publications as prototypical implementation, the reference to the publication must be stored.
- Define required Resources, SDKs and input restrictions for an implementations. The SDKs specify the supported Backends for the execution.
- The license of the implementation must be provided.

### Technical requirement
- In the most cases the source code is linked (e.g. github), but the source code can also be stored at the platform.

### Design requirement
- the source code can be uploaded and downloaded as zip artifact
- Contained License file should be identified and the information provided for the users.

>Note: Reference to RQ-6, RQ-9

**Comment by salmma** [comment]
handling of source code is currently in porgress
